routes/web.php
<?php
use App\Http\Controllers\FrontendController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontendController@index')->name('frontend.index');
Route::get('blogs/{dkc}', 'FrontendController@show')->name('frontend.show');
Route::get('blogs/categories/{category}', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('blogs/users/{user}', [FrontendController::class, 'user'])->name('frontend.user');

Route::get('mails/send', 'MailController@send')->name('mail.send');

Auth::routes();

Route::middleware(['auth'])->group(function(){

  Route::get('home', 'DkcController@index')->name('home');
  
  Route::resource('categories', 'CategoryController');
  
  Route::resource('tags', 'TagController');
  
  Route::resource('dkcs', 'DkcController');

  Route::resource('posts', 'PostController');

  Route::get('trashed-posts', 'PostController@trashed')->name('posts.trashed');
  
  Route::get('restore-post/{id}', 'PostController@restore')->name('posts.restore');


  
  Route::post('/upload/file', 'DkcController@upload')->name('dkcs.upload');

});

Route::middleware(['auth', 'admin'])->group(function(){

  Route::resource('users', 'UserController');
  Route::post('users/make-admin/{user}', 'UserController@makeAdmin')->name('users.make-admin');

});

app/Dkc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Dkc extends Model
{
  protected $dates = [
    'happened_on'
  ];
  
  protected $fillable = [
    'title',
    'detail',
    'happened_on',
    'user_id',
    'vdo',
  ];

  // protected $guarded = [];



  public function tags()
  {
    return $this->belongsToMany(Tag::class);
  }

  public function user()
  {
    return $this->belongsTo(User::class);
  }

  public function hasTag($tagId)
  {
    return in_array($tagId, $this->tags->pluck('id')->toArray());
  }

  public function images()
  {
    return $this->hasMany(DkcImage::class);
  }


  public function scopeSearched($query)
  {
    
    $search = request()->query('search');
    // $d = request()->query('d');
    // $m = request()->query('m');
    // $y = request()->query('y');

    if($search){
      $query->where('title', 'LIKE', "%{$search}%")->orWhere('detail', 'LIKE', "%{$search}%");
    }

    if(request()->query('d')){
      // $query->whereRaw("DAY(happened_on) = {$d}");
      $query->whereDay('happened_on', request()->query('d'));
    }

    if(request()->query('m')){
      // $query->whereRaw("MONTH(happened_on) = {$m}");
      $query->whereMonth('happened_on', request()->query('m'));
    }

    if(request()->query('y')){
      // $y = $y-543;
      // $query->whereRaw("YEAR(happened_on) = {$y}");
      $query->whereYear('happened_on', request()->query('y')-543);
    }
    // dd($query);
    return $query;

  }



  public function scopePublished($query)
  {
    return $query->where('happened_on', '<=', now());
  }

  // เพื่อดัดแปลงค่าจากฟิลด์ image ก่อนออกมา ด้วยการเติมชื่อโฟลเดอร์ไปข้างหน้า
  public function getImageAttribute($value)
  {
    return 'storage/'.$value;
  }

}

app/Http/Controllers/DkcController.php
<?php

namespace App\Http\Controllers;

use App\Dkc;
use App\Tag;
use App\DkcImage;
use Illuminate\Http\Request;
use App\Http\Requests\Dkcs\FormHistoryRequest;

class DkcController extends Controller
{
  private $months = [1 => 'ม.ค.', 2 => 'ก.พ.', 3 => 'มี.ค.', 4 => 'เม.ย.', 5 => 'พ.ค.', 6 => 'มิ.ย.', 7 => 'ก.ค.', 8 => 'ส.ค.', 9 => 'ก.ย.', 10 => 'ต.ค.', 11 => 'พ.ย.', 12 => 'ธ.ค.'];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $months = [1 => 'ม.ค.', 2 => 'ก.พ.', 3 => 'มี.ค.', 4 => 'เม.ย.', 5 => 'พ.ค.', 6 => 'มิ.ย.', 7 => 'ก.ค.', 8 => 'ส.ค.', 9 => 'ก.ย.', 10 => 'ต.ค.', 11 => 'พ.ย.', 12 => 'ธ.ค.'];
      return view('blog.dkc.index')
        ->withDkcs(Dkc::searched()->orderBy('happened_on','desc')->paginate(10))
        ->withMonths($this->months);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('blog.dkc.form')
        ->withTags(Tag::all())
        ->withMonths($this->months);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FormHistoryRequest $request)
    {
      $attribute = $request->all();
      $attribute['user_id'] = auth()->user()->id;
      $y = $request->y-543;
      $attribute['happened_on'] = "{$y}-{$request->m}-{$request->d}";

      $dkc = Dkc::create($attribute);

      if(isset($request->images)){
        foreach($request->images AS $reqimage)
        {

          $image = $reqimage->store('dkcs');

          $dkcimg = DkcImage::create([
            "dkc_id"=>$dkc->id,
            "path"=>$image,
          ]);
        }
      }

      if($request->tags){
        $dkc->tags()->attach($request->tags);
      }

      return redirect(route('dkcs.index'))->withStatus('เพิ่มข้อมูลเรียบร้อย');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Dkc  $dkc
     * @return \Illuminate\Http\Response
     */
    public function show(Dkc $dkc)
    {
      return view('blog.dkc.view')->withDkc($dkc);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dkc  $dkc
     * @return \Illuminate\Http\Response
     */
    public function edit(Dkc $dkc)
    {
      return view('blog.dkc.form')
      ->withDkc($dkc)
      ->withTags(Tag::all())
      ->withMonths($this->months);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dkc  $dkc
     * @return \Illuminate\Http\Response
     */
    public function update(FormHistoryRequest $request, Dkc $dkc)
    {
      $attribute = $request->all();
      $attribute['user_id'] = auth()->user()->id;
      $y = $request->y-543;
      $attribute['happened_on'] = "{$y}-{$request->m}-{$request->d}";
      $dkc->update($attribute);

      if(isset($request->images)){

        $DkcImages = DkcImage::where('dkc_id', $dkc->id)->get();
        // dd($DkcImages);
        foreach($DkcImages AS $DkcImage){
           $DkcImage->deleteImage(); // ลบรูป
           $DkcImage->delete(); // ลบ record
        }
       
        // DkcImage::where('dkc_id', $dkc->id)->delete();

        foreach($request->images AS $reqimage)
        {

          $image = $reqimage->store('dkcs');

          $dkcimg = DkcImage::create([
            "dkc_id"=>$dkc->id,
            "path"=>$image,
          ]);
        }
      }

      if($request->tags){
        $dkc->tags()->sync($request->tags);
      }

      return redirect(route('dkcs.index'))->withStatus('แก้ไขข้อมูลเรียบร้อย');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dkc  $dkc
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dkc $dkc)
    {
      $DkcImages = DkcImage::where('dkc_id', $dkc->id)->get();
      // dd($DkcImages);
      foreach($DkcImages AS $DkcImage){
         $DkcImage->deleteImage(); // ลบรูป
         $DkcImage->delete(); // ลบ record
      }
      $dkc->delete();
      return redirect(route('dkcs.index'))->withStatus('ลบข้อมูลเรียบร้อย');
    }


    public function upload(Request $request)
    {
      $path = $request->file->store('dkcs');
      return $path;
    }
}

resources/views/blog/dkc/form.blade.php
@extends('layouts.main')


@section('error')
  @if($errors->any())
    @foreach($errors->all() AS $error)  
      <div class="alert alert-danger">{{$error}}</div>
    @endforeach
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header">{{isset($dkc)?'แก้ไข':'เพิ่ม'}} เหตุการณ์</h4>
    <div class="card-body">
      <form action="{{isset($dkc)?route('dkcs.update', $dkc->id):route('dkcs.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        @if(isset($dkc))
          @method('PUT')
        @endif
        <div class="form-group">
          <label for="happened_on">วันที่</label>
          <div class="d-flex">
            <select name="d" id="d" class="form-control" style="width: 90px;">
              <option value="">วัน</option>
              @for($i = 1; $i <= 31; $i++)
                <option value="{{$i}}" 
                  @if($i==(isset($dkc)?$dkc->happened_on->format('d'):Carbon::now()->format('d')))
                    selected
                  @endif
                >{{$i}}</option>
              @endfor
            </select>
            <select name="m" id="m" class="form-control ml-2" style="width: 90px;">
              <option value="">เดือน</option>
              @foreach($months as $key=>$month)
                <option value="{{$key}}"
                  @if($key==(isset($dkc)?$dkc->happened_on->format('m'):Carbon::now()->format('m')))
                    selected
                  @endif
                >{{$month}}</option>
              @endforeach
            </select>
            <select name="y" id="y" class="form-control ml-2" style="width: 90px;">
              <option value="">ปี</option>
              @for($i = (Carbon::now()->format('Y')+543); $i >= 2512; $i--)
                <option value="{{$i}}" 
                  @if($i==(isset($dkc)?($dkc->happened_on->format('Y')+543):(Carbon::now()->format('Y')+543)))
                    selected
                  @endif
                >{{$i}}</option>
              @endfor
            </select>
          </div>          
          {{-- <input type="text" name="happened_on" id="happened_on" class="form-control" value="{{old('happened_on', isset($dkc)?$dkc->happened_on:Carbon::now())}}"> --}}
        </div>        
        <div class="form-group">
          <label for="title">เหตุการณ์</label>
          <input type="text" name="title" id="title" class="form-control" value="{{old('title', isset($dkc)?$dkc->title:'')}}">
        </div>
        <div class="form-group">
          <label for="detail">รายละเอียด</label>
          <input type="hidden" name="detail" id="detail" class="form-control" value="{{old('detail', isset($dkc)?$dkc->detail:'')}}">
          <trix-editor input="detail"></trix-editor>
        </div>
        <div class="form-group">
          <label for="">รูปภาพ</label>
          @if(isset($dkc))
            <div>
              @foreach($dkc->images AS $image)
                <img src="{{asset($image->path)}}" class="w-25 mr-2 mb-2">
              @endforeach
            </div>
          @endif
          <input type="file" name="images[]" id="images" multiple >
        </div>
        <div class="form-group">
          <label for="vdo">YouTube VDO link</label>
          <input type="text" name="vdo" id="vdo" class="form-control" value="{{old('vdo', isset($dkc)?$dkc->vdo:'')}}">
        </div>
        <div class="form-group">
          <label for="tags">Tags</label>
          <select name="tags[]" id="tags" class="form-control select2" multiple>
            <option value="">-Choose-</option>
            @foreach($tags AS $tag)
              <option value="{{$tag->id}}" 
                @if(isset($dkc))
                  {{$dkc->hasTag($tag->id)?"selected":""}}  
                @endif
              >{{$tag->name}}</option>
            @endforeach
          </select>
        </div>
        <button class="btn btn-primary">บันทึก</button>
        <a href="{{route('dkcs.index')}}" class="btn btn-default ml-2">ยกเลิก</a>
      </form>
    </div>
  </div>
@endsection

@section('css')
  {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.0/trix.css"> --}}
  {{-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"> --}}

@endsection

@section('scripts')
  {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.0/trix.js"></script> --}}
  {{-- <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script> --}}

  <script>
    document.getElementById('title').focus();

    flatpickr("#happened_on", {
      enableTime: false,
      enableSeconds: false,
      locale: Thai
    })

    $(function(){

      $(".select2").select2();

      // http://plugins.krajee.com/file-input/plugin-options#language
      $("#images").fileinput({
        theme: "fas",
        showUpload:false, 
        showCaption:false, 
        showCancel:false, 
        hideThumbnailContent:false,  
        fileActionSettings: {
          // showZoom:false,
        },
      });



      var element = document.querySelector("trix-editor")
      


      var HOST = "/upload/file"
      addEventListener("trix-attachment-add", function(event) {
          if (event.attachment.file) {
              uploadFileAttachment(event.attachment)
          }
      })
      function uploadFileAttachment(attachment) {
          uploaded = uploadFile(attachment.file, setProgress, setAttributes)
          function setProgress(progress) {
              attachment.setUploadProgress(progress)
          }
          function setAttributes(attributes) {
              // console.log(attachment)
              attachment.setAttributes(attributes)
              
          }
          // console.log(uploaded)
          attachment.remove();
      }
      function uploadFile(file, progressCallback, successCallback) {

          var formData = createFormData(file)
          var xhr = new XMLHttpRequest()
          xhr.open("POST", HOST, true)
          xhr.upload.addEventListener("progress", function(event) {
              var progress = event.loaded / event.total * 100
              progressCallback(progress) 
          })
          xhr.addEventListener("load", function(event) {
              if (xhr.status == 204) {
                  var attributes = {
                      url: HOST,
                      href: HOST + "?content-disposition=attachment"
                  }
                  // console.log(5555)
                  successCallback(attributes)
              }
              // successCallback(`/storage/${event.target.responseText}`)
              current_range = element.editor.getSelectedRange()
              element.editor.setSelectedRange(current_range)
              element.editor.insertHTML(`<img src="/storage/${event.target.responseText}" class='img-fluid'>`)
              
          })
          xhr.send(formData)
          return event.target.responseText
      }

      function createFormData(file) {
          var data = new FormData()
          _token = document.querySelector('[name=_token]').value;
          data.append("_token", _token)
          data.append("file", file)
          data.append("Content-Type", file.type)
          return data
      }




      
    })





    


  </script>
@endsection

resources/views/blog/dkc/front.blade.php
@extends('layouts.main')

@section('title', 'Posts')

@section('error')
  @if(session('error'))
    <div class="alert alert-danger">{{session('error')}}</div>
  @endif
@endsection

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">Posts</div>
      <a href="{{route('posts.create')}}" class="btn btn-secondary">Add</a>
    </h4>
    <div class="card-body">
      @if($posts->count())
      <table class="table mt-2">
        <thead>
          <tr>
            <th>#</th>
            <th>Image</th>
            <th>Title</th>
            <th>Desctipion</th>
            <th>Category</th>
            <th>Tag</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($posts AS $post)
          <tr>
            <td>{{$post->id}}</td>
            <td><img src="{{asset('storage/'.$post->image)}}" width="100"></td>
            <td>{{$post->title}}</td>
            <td>{{$post->description}}</td>
            <td>{{$post->category->name}}</td>
            <td>
              @foreach($post->tags AS $tag)
                <a href="" class="badge badge-info">{{$tag->name}}</a>
              @endforeach
            </td>
            <td>
              <form action="{{route('posts.destroy', $post->id)}}" method="post" class="d-inline-block ml-2">
                <div class="btn-group" role="group">

                  <a href="{{route('posts.show', $post->id)}}" class="btn  btn-outline-primary btn-sm">View</a>
                  <a href="{{route('posts.edit', $post->id)}}" class="btn  btn-outline-secondary btn-sm">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                </div>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
      @else
        <h2 class="text-center">No Posts Yet</h2>
      @endif
    </div>
  </div>
@endsection

resources/views/blog/dkc/index.blade.php
@extends('layouts.main')

@section('title', 'รวมเหตุการณ์')

@section('error')
  @if(session('error'))
    <div class="alert alert-danger">{{session('error')}}</div>
  @endif
@endsection

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">
        <h4>Dhammakaya History</h4>
        <small>บันทึกเหตุการณ์วัดพระธรรมกาย</small>
      </div>
      <a href="{{route('dkcs.create')}}" class="btn btn-primary d-flex align-items-center"><i class="fa fa-plus mr-1"></i> เพิ่มใหม่</a>
    </h4>
    <div class="card-body">
      <form action="" method="GET">
        <div class="form-group row">
          <div class="col-sm-3 mb-2">
            <input type="text" class="form-control" name="search" placeholder="ค้นหา.." value="{{request()->query('search')}}">
          </div>
          <div class="col-sm-6 d-flex mb-2">
            <select name="d" id="d" class="form-control">
              <option value="">วัน</option>
              @for($i = 1; $i <= 31; $i++)
                <option value="{{$i}}" 
                  @if($i==request()->query('d'))
                    selected
                  @endif
                >{{$i}}</option>
              @endfor
            </select>
            <select name="m" id="m" class="form-control">
              <option value="">เดือน</option>
              @foreach($months as $key=>$month)
                <option value="{{$key}}"
                  @if($key==request()->query('m'))
                    selected
                  @endif
                >{{$month}}</option>
              @endforeach
            </select>
            <select name="y" id="y" class="form-control">
              <option value="">ปี</option>
              @for($i = (Carbon::now()->format('Y')+543); $i >= 2512; $i--)
                <option value="{{$i}}" 
                  @if($i==request()->query('y'))
                    selected
                  @endif
                >{{$i}}</option>
              @endfor
            </select>
          </div>
          <div class="col-sm-3">
            <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-search"></i> ค้นหา</button>
          </div>
        </div>
      </form>
      @if($dkcs->count())
      <div class="table-responsive">
        <table class="table mt-4">
          <thead>
            <tr>
              <th>วันที่</th>
              <th>เหตุการณ์</th>
              <th>รายละเอียด</th>
              <th>Tag</th>
              <th>รูปภาพ</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach($dkcs AS $dkc)
            <tr>
              <td class='text-nowrap'>{{$dkc->happened_on->locale('th')->isoFormat('dd D MMM')}} {{($dkc->happened_on->isoFormat('YYYY')+543)}}</td>
              {{-- <td><i>{{$dkc->happened_on->locale('th')->diffForHumans()}}</i></td> --}}
              <td>{{$dkc->title}}</td>
              <td>{{Str::words(str_replace('&nbsp;',' ', strip_tags($dkc->detail)), '8')}}
                @if(isset($dkc->vdo))
                <div><a href="{{$dkc->vdo}}" class="" target='_blank'>{{$dkc->vdo}}</a></div>
                @endif
              </td>
              <td>
                @foreach($dkc->tags AS $tag)
                  <a href="" class="badge badge-light">{{$tag->name}}</a>
                @endforeach
              </td>
              <td>
                @foreach($dkc->images AS $image)
                  <img src="{{asset($image->path)}}" width="100">
                @endforeach
              </td>
              <td>
                <form action="{{route('dkcs.destroy', $dkc->id)}}" method="post" class="d-inline-block ml-2 form-delete" >
                  <div class="btn-group" role="group">

                    <a href="{{route('dkcs.show', $dkc->id)}}" class="btn  btn-outline-primary btn-sm">ดู</a>
                    <a href="{{route('dkcs.edit', $dkc->id)}}" class="btn  btn-outline-secondary btn-sm">แก้ไข</a>
                      @csrf
                      @method('DELETE')
                      <button type="submit" class="btn btn-outline-danger btn-form-delete btn-sm">ลบ</button>
                  </div>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      {{$dkcs->links()}}
      @else
        <h3 class="text-center mt-4">ไม่มีข้อมูล</h3>
      @endif
    </div>
  </div>

@endsection


@section('scripts')

<script>
  $(function(){

    // confirm before delete
    $(document).on('click', '.btn-form-delete', function(e){
      e.preventDefault();
      this_ = $(this);
      return bootbox.confirm({
        message: "ยืนยันการลบข้อมูล?",
        buttons: {
            confirm: {
                label: 'ยืนยัน',
                className: 'btn-primary'
            },
            cancel: {
                label: 'ยกเลิก',
                className: 'btn-default'
            }
        },
        callback: function (result) {
          if(result===true){
            this_.closest('form').submit();
          }
        }
      });
    });


  });
</script>
@endsection

resources/views/blog/dkc/trashed.blade.php
@extends('layouts.main')

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">Trashed Post</div>
    </h4>
    <div class="card-body">
      
      <table class="table mt-2">
        <thead>
          <tr>
            <th>#</th>
            <th>Image</th>
            <th>Title</th>
            <th>Desctipion</th>
            <th>Content</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($trashedPosts AS $post)
          <tr>
            <td>{{$post->id}}</td>
            <td><img src="{{asset('storage/'.$post->image)}}" width="100"></td>
            <td>{{$post->title}}</td>
            <td>{{$post->description}}</td>
            <td>{!!$post->content!!}</td>
            <td>
              <a href="{{route('posts.restore', $post->id)}}" class="btn  btn-outline-info">Restore</a>
              <form action="{{route('posts.destroy', $post->id)}}" method="post" class="d-inline-block ml-2">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-outline-danger">Permanently Delete</button>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/blog/dkc/view.blade.php
@extends('layouts.main')

@section('content')
  <div class="card">
    @foreach($dkc->images AS $image)
      <img class="card-img-top" src="{{asset($image->path)}}" >
    @endforeach
    <div class="card-body">
      <h1>{{$dkc->title}}</h1>
      <p class="mb-0"><a class="text-dark" href="{{route('frontend.show', $dkc)}}">{{$dkc->happened_on->locale('th')->isoFormat('dd D MMM YYYY')}}</a></p>
      <hr>
      <p>{!!$dkc->detail!!}</p>
      @if(isset($dkc->vdo))
        <h5><a href="{{$dkc->vdo}}" class="btn btn-danger" target='_blank'>VDO Link</a></h5>
      @endif
      @foreach($dkc->tags AS $tag)
        <a class="badge badge-pill badge-secondary" href="{{route('frontend.tag',$tag)}}">{{$tag->name}}</a>
      @endforeach
      <div class="mt-3"><a href="{{route('dkcs.index')}}" class="btn btn-primary">Back</a></div>
    </div>
  </div>
@endsection