routes/web.php
<?php
use App\Http\Controllers\FrontendController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontendController@index')->name('frontend.index');
Route::get('blogs/{dkc}', 'FrontendController@show')->name('frontend.show');
Route::get('blogs/categories/{category}', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('blogs/users/{user}', [FrontendController::class, 'user'])->name('frontend.user');

Route::get('mails/send', 'MailController@send')->name('mail.send');

Auth::routes();

Route::middleware(['auth'])->group(function(){

  Route::get('home', 'DkcController@index')->name('home');
  
  Route::resource('categories', 'CategoryController');
  
  Route::resource('tags', 'TagController');
  
  Route::resource('dkcs', 'DkcController');

  Route::resource('posts', 'PostController');

  Route::get('trashed-posts', 'PostController@trashed')->name('posts.trashed');
  
  Route::get('restore-post/{id}', 'PostController@restore')->name('posts.restore');


  
  Route::post('/upload/file', 'DkcController@upload')->name('dkcs.upload');

});

Route::middleware(['auth', 'admin'])->group(function(){

  Route::resource('users', 'UserController');
  Route::post('users/make-admin/{user}', 'UserController@makeAdmin')->name('users.make-admin');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin()
    {
      return $this->role === 'admin';
    }

    public function posts()
    {
      return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('user.index')->withUsers(User::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function makeAdmin(User $user)
    {
      $user->role= "admin";
      $user->save();
      return redirect(route('users.index'))->withStatus('User made admin successfully.');
    }
}

resources/views/user/index.blade.php
@extends('layouts.main')

@section('title', 'Users')

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">Users</div>
      <a href="{{route('users.create')}}" class="btn btn-secondary">Add</a>
    </h4>
    <div class="card-body">
      @if($users->count())
      <table class="table mt-2">
        <thead>
          <tr>
            <th>#</th>
            <th>Image</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($users AS $user)
          <tr>
            <td>{{$user->id}}</td>
            <td><img src="{{Gravatar::src($user->email)}}" class="img-fluid rounded-circle"></td>
            <td>{{$user->name}}</td>
            <td>{{$user->email}}</td>
            <td>
              {{$user->role}}
              @if(!$user->isAdmin())
                <form action="{{route('users.make-admin',$user->id)}}" method="post">
                  @csrf
                  <button type="submit" class="btn btn-primary">Make Admin</button>
                </form>
              @endif
            </td>
            <td>
              <form action="{{route('users.destroy', $user->id)}}" method="post" class="d-inline-block ml-2">
                  <div class="btn-group" role="group">
  
                    <a href="{{route('users.show', $user->id)}}" class="btn  btn-outline-primary btn-sm">View</a>
                    <a href="{{route('users.edit', $user->id)}}" class="btn  btn-outline-secondary btn-sm">Edit</a>
                      @csrf
                      @method('DELETE')
                      <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                  </div>
                </form>              
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
      @else
        <h2 class="text-center">No Users Yet</h2>
      @endif
    </div>
  </div>
@endsection