routes/web.php
<?php
use App\Http\Controllers\FrontendController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontendController@index')->name('frontend.index');
Route::get('blogs/{dkc}', 'FrontendController@show')->name('frontend.show');
Route::get('blogs/categories/{category}', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('blogs/users/{user}', [FrontendController::class, 'user'])->name('frontend.user');

Route::get('mails/send', 'MailController@send')->name('mail.send');

Auth::routes();

Route::middleware(['auth'])->group(function(){

  Route::get('home', 'DkcController@index')->name('home');
  
  Route::resource('categories', 'CategoryController');
  
  Route::resource('tags', 'TagController');
  
  Route::resource('dkcs', 'DkcController');

  Route::resource('posts', 'PostController');

  Route::get('trashed-posts', 'PostController@trashed')->name('posts.trashed');
  
  Route::get('restore-post/{id}', 'PostController@restore')->name('posts.restore');


  
  Route::post('/upload/file', 'DkcController@upload')->name('dkcs.upload');

});

Route::middleware(['auth', 'admin'])->group(function(){

  Route::resource('users', 'UserController');
  Route::post('users/make-admin/{user}', 'UserController@makeAdmin')->name('users.make-admin');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class Post extends Model
{
  use SoftDeletes;

  protected $dates = [
    'published_at'
  ];
  
  protected $fillable = [
    'title',
    'description',
    'content',
    'image',
    'published_at',
    'user_id',
    'category_id',
  ];

  /*
   Delete Image
  */
  public function deleteImage()
  {
    Storage::delete($this->image);
  }

  public function category()
  {
    return $this->belongsTo(Category::class);
  }

  public function tags()
  {
    return $this->belongsToMany(Tag::class);
  }

  public function user()
  {
    return $this->belongsTo(User::class);
  }

  public function hasTag($tagId)
  {
    return in_array($tagId, $this->tags->pluck('id')->toArray());
  }

  public function carbon_published_at()
  {
    return Carbon::createFromFormat('Y-m-d H:i:s', $this->published_at)->locale('th');
  }


  public function scopeSearched($query)
  {
    $search = request()->query('search');

    if(!$search){
      return $query->published();
    }

    return $query->published()->where('title', 'LIKE', "%{$search}%");

  }

  public function scopePublished($query)
  {
    return $query->where('published_at', '<=', now());
  }

  // เพื่อดัดแปลงค่าจากฟิลด์ image ก่อนออกมา ด้วยการเติมชื่อโฟลเดอร์ไปข้างหน้า
  public function getImageAttribute($value)
  {
    return 'storage/'.$value;
  }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Category;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\Posts\CreatePostsRequest;
use App\Http\Requests\Posts\UpdatePostsRequest;
use Illuminate\Support\Facades\Storage;
class PostController extends Controller
{
  
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('blog.post.index')->with('posts', Post::paginate(3));
    }

    public function welcome()
    {
      return view('welcome')
        ->withPosts(Post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

      return view('blog.post.form')
        ->with('categories', Category::all())
        ->withTags(Tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostsRequest $request)
    {
      $image = $request->image->store('posts');
      $attribute = $request->all();
      $attribute['image'] = $image;
      $attribute['user_id'] = auth()->user()->id;
      // dd($attribute);
      $post = Post::create($attribute);

      if($request->tags){
        $post->tags()->attach($request->tags);
      }

      return redirect(route('posts.index'))->with('status', 'Post Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
      return view('blog.post.view')->withPost($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
      return view('blog.post.form')
        ->with('post', $post)
        ->with('categories', Category::all())
        ->withTags(Tag::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostsRequest $request, Post $post)
    {
      $data = $request->all();      
      if($request->hasFile('image')){

        $image = $request->image->store('posts');

        //Storage::delete($post->image);
        $post->deleteImage();

        $data["image"] = $image;
      }
      $post->update($data);

      if($request->tags){
        $post->tags()->sync($request->tags);
      }

      return redirect(route('posts.index'))->withStatus('Update Successful');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    // public function destroy(Post $post)
    // {
    //   $post->delete();
    //   return redirect(route('posts.index'))->with('status', 'Delete Successful');
    // }

    public function destroy($id)
    {
      $post = Post::withTrashed()->where('id', $id)->firstOrFail();
      if($post->trashed()){
        //Storage::delete($post->image);
        $post->deleteImage();

        $post->forceDelete();
      }else{
        $post->delete();
      }
      return redirect(route('posts.index'))->with('status', 'Delete Successful');
    }


    public function trashed(){
      $trashed = Post::onlyTrashed()->get();
      return view('blog.post.trashed')->withTrashedPosts($trashed);
    }

    public function restore($id){
      $post = Post::withTrashed()->where('id', $id)->first();
      $post->restore();
      return redirect(route('posts.index'))->withStatus('Restore Successful');
    }



}

resources/views/blog/post/form.blade.php
@extends('layouts.main')


@section('error')
  @if($errors->any())
    @foreach($errors->all() AS $error)  
      <div class="alert alert-danger">{{$error}}</div>
    @endforeach
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header">{{isset($post)?'Edit':'Create'}} post</h4>
    <div class="card-body">
      <form action="{{isset($post)?route('posts.update', $post->id):route('posts.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        @if(isset($post))
          @method('PUT')
        @endif
        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" name="title" id="title" class="form-control" value="{{old('title', isset($post)?$post->title:'')}}">
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea type="text" name="description" id="description" class="form-control" >{{old('description', isset($post)?$post->description:'')}}</textarea>
        </div>
        <div class="form-group">
          <label for="content">Content</label>
          <input type="hidden" name="content" id="content" class="form-control" value="{{old('content', isset($post)?$post->content:'')}}">
          <trix-editor input="content"></trix-editor>
        </div>
        <div class="form-group">
          <label for="published_at">Published at</label>
          <input type="text" name="published_at" id="published_at" class="form-control" value="{{old('published_at', isset($post)?$post->published_at:'')}}">
        </div>
        <div class="form-group">
          <label for="category_id">Category</label>
          <select name="category_id" id="category_id" class="form-control">
            <option value="">-Choose-</option>
            @foreach($categories AS $category)
              <option value="{{$category->id}}" 
                @if(isset($post))
                  {{($category->id==$post->category_id)?"selected":""}}  
                @endif
              >{{$category->name}}</option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="tags">Tags</label>
          <select name="tags[]" id="tags" class="form-control select2" multiple>
            <option value="">-Choose-</option>
            @foreach($tags AS $tag)
              <option value="{{$tag->id}}" 
                @if(isset($post))
                  {{$post->hasTag($tag->id)?"selected":""}}  
                @endif
              >{{$tag->name}}</option>
            @endforeach
          </select>
        </div>
        @if(isset($post))
          <div class="form-group">
            <img src="{{asset('storage/'.$post->image)}}" class="img-fluid">
          </div>
        @endif
        <div class="form-group">
          <label for="image">Image</label>
          <input type="file" name="image" id="image" class="form-control" value="{{old('image', isset($post)?$post->image:'')}}">
        </div>
        <button class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
@endsection

@section('css')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.0/trix.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.1.0/trix.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

  <script>
    document.getElementById('title').focus();
    flatpickr("#published_at", {
      enableTime: true,
      enableSeconds: true
    })

    $(function(){
      $(".select2").select2();
    })
  </script>
@endsection

resources/views/blog/post/front.blade.php
@extends('layouts.main')

@section('title', 'Posts')

@section('error')
  @if(session('error'))
    <div class="alert alert-danger">{{session('error')}}</div>
  @endif
@endsection

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">Posts</div>
      <a href="{{route('posts.create')}}" class="btn btn-secondary">Add</a>
    </h4>
    <div class="card-body">
      @if($posts->count())
      <table class="table mt-2">
        <thead>
          <tr>
            <th>#</th>
            <th>Image</th>
            <th>Title</th>
            <th>Desctipion</th>
            <th>Category</th>
            <th>Tag</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($posts AS $post)
          <tr>
            <td>{{$post->id}}</td>
            <td><img src="{{asset('storage/'.$post->image)}}" width="100"></td>
            <td>{{$post->title}}</td>
            <td>{{$post->description}}</td>
            <td>{{$post->category->name}}</td>
            <td>
              @foreach($post->tags AS $tag)
                <a href="" class="badge badge-info">{{$tag->name}}</a>
              @endforeach
            </td>
            <td>
              <form action="{{route('posts.destroy', $post->id)}}" method="post" class="d-inline-block ml-2">
                <div class="btn-group" role="group">

                  <a href="{{route('posts.show', $post->id)}}" class="btn  btn-outline-primary btn-sm">View</a>
                  <a href="{{route('posts.edit', $post->id)}}" class="btn  btn-outline-secondary btn-sm">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                </div>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
      @else
        <h2 class="text-center">No Posts Yet</h2>
      @endif
    </div>
  </div>
@endsection

resources/views/blog/post/index.blade.php
@extends('layouts.main')

@section('title', 'Posts')

@section('error')
  @if(session('error'))
    <div class="alert alert-danger">{{session('error')}}</div>
  @endif
@endsection

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">Posts</div>
      <a href="{{route('posts.create')}}" class="btn btn-secondary">Add</a>
    </h4>
    <div class="card-body">
      @if($posts->count())
      <table class="table mt-2">
        <thead>
          <tr>
            <th>#</th>
            <th>Image</th>
            <th>Title</th>
            <th>Desctipion</th>
            <th>Category</th>
            <th>Tag</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($posts AS $post)
          <tr>
            <td>{{$post->id}}</td>
            <td><img src="{{asset($post->image)}}" width="100"></td>
            <td>{{$post->title}}</td>
            <td>{{$post->description}}</td>
            <td>{{$post->category->name}}</td>
            <td>
              @foreach($post->tags AS $tag)
                <a href="" class="badge badge-info">{{$tag->name}}</a>
              @endforeach
            </td>
            <td>
              <form action="{{route('posts.destroy', $post->id)}}" method="post" class="d-inline-block ml-2">
                <div class="btn-group" role="group">

                  <a href="{{route('posts.show', $post->id)}}" class="btn  btn-outline-primary btn-sm">View</a>
                  <a href="{{route('posts.edit', $post->id)}}" class="btn  btn-outline-secondary btn-sm">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                </div>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
      {{$posts->links()}}
      @else
        <h2 class="text-center">No Posts Yet</h2>
      @endif
    </div>
  </div>
@endsection

resources/views/blog/post/trashed.blade.php
@extends('layouts.main')

@section('status')
  @if(session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
  @endif
@endsection

@section('content')
  <div class="card">
    <h4 class="card-header d-flex">
      <div class="mr-auto">Trashed Post</div>
    </h4>
    <div class="card-body">
      
      <table class="table mt-2">
        <thead>
          <tr>
            <th>#</th>
            <th>Image</th>
            <th>Title</th>
            <th>Desctipion</th>
            <th>Content</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($trashedPosts AS $post)
          <tr>
            <td>{{$post->id}}</td>
            <td><img src="{{asset('storage/'.$post->image)}}" width="100"></td>
            <td>{{$post->title}}</td>
            <td>{{$post->description}}</td>
            <td>{!!$post->content!!}</td>
            <td>
              <a href="{{route('posts.restore', $post->id)}}" class="btn  btn-outline-info">Restore</a>
              <form action="{{route('posts.destroy', $post->id)}}" method="post" class="d-inline-block ml-2">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-outline-danger">Permanently Delete</button>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/blog/post/view.blade.php
@extends('layouts.main')

@section('content')
  <div class="card">
    <img src="{{asset('storage/'.$post->image)}}" class="card-img-top">
    <div class="card-body">
      <h1>{{$post->title}}</h1>
      <h4>{{$post->description}}</h4>
      @if(isset($post->published_at))
        <p class="card-title">
          ({{$post->carbon_published_at()->format('l jS \\of F Y')}}) - 
          {{Carbon::createFromFormat('Y-m-d H:i:s',$post->published_at)->locale('th')->diffForHumans()}}
        </p>
      @endif
      <hr>
      <p>{!!$post->content!!}</p>
      <div class="mt-3"><a href="{{route('posts.index')}}" class="btn btn-primary">Back</a></div>
    </div>
  </div>
@endsection