routes/web.php
<?php
use App\Http\Controllers\FrontendController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'FrontendController@index')->name('frontend.index');
Route::get('blogs/{dkc}', 'FrontendController@show')->name('frontend.show');
Route::get('blogs/categories/{category}', [FrontendController::class, 'category'])->name('frontend.category');
Route::get('blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('frontend.tag');
Route::get('blogs/users/{user}', [FrontendController::class, 'user'])->name('frontend.user');

Route::get('mails/send', 'MailController@send')->name('mail.send');

Auth::routes();

Route::middleware(['auth'])->group(function(){

  Route::get('home', 'DkcController@index')->name('home');
  
  Route::resource('categories', 'CategoryController');
  
  Route::resource('tags', 'TagController');
  
  Route::resource('dkcs', 'DkcController');

  Route::resource('posts', 'PostController');

  Route::get('trashed-posts', 'PostController@trashed')->name('posts.trashed');
  
  Route::get('restore-post/{id}', 'PostController@restore')->name('posts.restore');


  
  Route::post('/upload/file', 'DkcController@upload')->name('dkcs.upload');

});

Route::middleware(['auth', 'admin'])->group(function(){

  Route::resource('users', 'UserController');
  Route::post('users/make-admin/{user}', 'UserController@makeAdmin')->name('users.make-admin');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="icon" href="{{asset('assets/img/icon/dkcicon.png')}}">
    <link rel="stylesheet" href="{{mix('css/main.css')}}">
    @yield('css')
</head>
<body>
    @include('layouts.navbar')

    <div class="container">

        <div class="row my-2">
          <div class="col">
            @yield('error')
            @yield('status')      
          </div>
        </div>

        <div class="row">
            {{-- <div class="col-3">
              @include('layouts.sidebar')
            </div> --}}
            <div class="col">
                @yield('content')
            </div>
        </div>
    </div>

    <script src="{{asset('js/main.js')}}"></script>
    @yield('scripts')
</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-dark navbar-expand-sm bg-primary mb-3">
  <a href="{{route('dkcs.index')}}" class="navbar-brand">History072</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navmenu" aria-controls="navmenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navmenu">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {{-- <li class="nav-item {{ Route::currentRouteName()=='home' ? 'active' : '' }}">
          <a class="nav-link" href="{{route('home')}}">Home</a>
        </li> --}}
        <li class="nav-item {{ Route::currentRouteName()=='dkcs.index' ? 'active' : '' }} ">
          <a class="nav-link" href="{{route('dkcs.index')}}">History</a>
        </li>
        <li class="nav-item {{ Route::currentRouteName()=='tags.index' ? 'active' : '' }}">
          <a class="nav-link" href="{{route('tags.index')}}">Tag</a>
        </li>
        <li class="nav-item {{ Route::currentRouteName()=='frontend.index' ? 'active' : '' }}">
          <a class="nav-link" href="{{route('frontend.index')}}" target="_blank">ดูหน้าเว็บ</a>
        </li>
        {{-- <li class="nav-item">
          <a class="nav-link" href="{{route('mail.send')}}" target="_blank">Email</a>
        </li> --}}
      </ul>
      <div class="my-2 my-lg-0">
        <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" >{{isset(Auth::user()->name)?Auth::user()->name:""}} </button>
          <div class="dropdown-menu dropdown-menu-right">
            <a href="" class="dropdown-item">Profile</a>
            <a href="" class="dropdown-item">Change Password</a>
            <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
            document.getElementById('logout-form').submit();">Sign Out</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
          </div>
        </div>
      </div>
    </div> 
</nav>

resources/views/layouts/sidebar.blade.php
<div class="list-group">
  
  <a href="/home" class="list-group-item list-group-item-action">Home</a>

  <a href="{{route('dkcs.index')}}" class="list-group-item list-group-item-action">เหตุการณ์</a>  


  @if(auth()->user()->isAdmin())
    <a href="{{route('users.index')}}" class="list-group-item list-group-item-action">Users</a>
  @endif

  {{-- <a href="{{route('posts.index')}}" class="list-group-item list-group-item-action">Posts</a>

  <a href="{{route('categories.index')}}" class="list-group-item list-group-item-action">Categories</a> --}}

  <a href="{{route('tags.index')}}" class="list-group-item list-group-item-action">Tags</a>


</div>
{{-- <div class="list-group mt-5">
  <a href="{{route('posts.trashed')}}" class="list-group-item list-group-item-action">Trashed Posts</a>
</div> --}}